### ISSUE TITLE
Crash when transaction uses expression

### ISSUE THREAD

**Issue by jrpie** [chvp/NanoLedger#189]
##### Reproduction steps

  1. Use a ledgerfile containing the following:
```
2024-10-11 * test
    Expenses:Test   (2  * 3 €)
    Assets:Checking
```
  2. Start app
  3. App briefly shows a loading screen, then crashes 
 ```
type: crash
osVersion: google/lynx/lynx:14/AP2A.240905.003/2024092900:user/release-keys
package: be.chvp.nanoledger:60200
process: be.chvp.nanoledger
processUptime: 369 + 309 ms
installer: com.android.packageinstaller

java.lang.NullPointerException
	at be.chvp.nanoledger.data.parser.TransactionParserKt.extractAmount(TransactionParser.kt:77)
	at be.chvp.nanoledger.data.parser.TransactionParserKt.extractPosting(TransactionParser.kt:55)
	at be.chvp.nanoledger.data.parser.TransactionParserKt.extractTransactions(TransactionParser.kt:28)
	at be.chvp.nanoledger.data.LedgerRepository.readFrom(LedgerRepository.kt:180)
	at be.chvp.nanoledger.ui.main.MainViewModel$refresh$1.invokeSuspend(MainViewModel.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5a7b855, Dispatchers.IO]
```

##### Expected behaviour

Not crashing. Even invalid files should be handled gracefully.

##### System information

Android 14 (GrapheneOS)
App version 0.6.1, versionCode 60200

**Comment by chvp** [comment]
Ah, I didn't even know this was possible. I'll try to get to this ASAP, but I don't have a lot of time this weekend or the coming week, sadly. I'll do my best to squeeze it in, but no promises.

**Comment by alerque** [comment]
There are actually quite a number of expression types that are not supported. Before launching into just fixing one it might be worth reviewing them all and deciding on a game plan. One of the issues here is that `ledger` and `hledger` both support advanced expressions of various types and it is not possible to reliably parse *both* sets of possibilities because there is some overlap that would conflict.

My understanding was that NanoLedger was only targeting a small subset of ledger syntax for now that happened to be 100% compatible with either CLI tool. My solution is to keep NanoLedger off of my main ledger files and just let it have it's own simplified one and include that in my main ledger.

If the goal becomes to support all the possible syntax iterations that would be **great**, but it should probably be done in an orderly fashion first having a toggle for which set of parsing rules to use, then adapting all the parser rules for that grammar.

**Comment by chvp** [comment]
Supporting everything is definitely not the plan. My idea here is to not crash and display the amount correctly, but when a transaction that contains this syntax is edited, the fields for that amount will not be filled.

**Comment by jrpie** [comment]
What about just copying the expression verbatim in the field for the amount? That way everyone could use whatever syntax their ledger/hledger/whatever supports and the app doesn't need to know about it.

**Comment by jrpie** [comment]
> I'll do my best to squeeze it in, but no promises.

No worries, if this is a free time project treat it as such. (If I had time, I would dig into the code and try to fix it myself, but I'm busy as well ^^)

@alerque's sugesstion of simply using multiple files is perfectly fine as a workaround, so for me this is not an urgent issue

**Comment by chvp** [comment]
> What about just copying the expression verbatim in the field for the amount? That way everyone could use whatever syntax their ledger/hledger/whatever supports and the app doesn't need to know about it.

The app verifies that the transaction balances before allowing it to be added, so that's not an option I'm afraid. (And I'm not really willing to compromise on that functionality, since that's one of the main features of the app for me.)
