### ISSUE TITLE
Editing transactions

### ISSUE THREAD

**Issue by chvp** [chvp/NanoLedger#49]
Edit transactions isn't trivial, because the parser throws away everything that isn't strictly what it needs. To be able to edit a transaction, we need to keep a transaction's "source". This might include extraneous data such as leading comments if we want to be able to write out the entire file, so we need to be careful that editing a transaction doesn't delete too much.

**Comment by alerque** [comment]
Edit (and delete, c.f. #48) are pretty fundamental. I understand why it is hard to implement, but I think there should be some provision for this. It might even call far a separate optional parser/app mode that enables this feature and errors or falls back to append-only mode if the parser hits anything it can't round trip. I could cope with only having a limited subset of ledger syntax as output by the app in order to get this feature.

I could probably cope myself, but this is blocker requirement in order to get my wife using some sort of data entry. I can figure out how to sync and edit other issues later, but if she can't fix anything as she's inputting it in we're going to have a mess and are worse off than our current note-taking-app solution.

**Comment by alerque** [comment]
Does deletion having just landed give hope that enough of the barriers to editing have been conquered and that his is soon to come?

**Comment by chvp** [comment]
There's still a few complexities I have to think about before I can do editing, but it should be do-able. I'm not making any promises on how soon this will happen though. (I am still just volunteering my time, after all.)

**Comment by lrq3000** [comment]
Just another vote for this very necessary feature, otherwise the app is perfectly usable.
